#language: ruby

services:
  - docker

before_install:
# install flutter dependencies
- bash -x ./script/install.sh --local
# install and start emulator
- bash -x ./script/emulator.sh 

script:
- bash -x ./script/run-test.sh flutter_app
